main: de.kid2407.bahnplugin.BahnPlugin
version: 1.2.2
name: BahnPlugin
commands:
  bahn:
    description: Gibt den Bahnhof zu dem angegebenen Spieler zurueck oder passt diesen an
    usage: "/bahn [help|get|set|delete] <spielername> [bahnhof]"
    permission: bahnplugin.use