main: de.kid2407.bahnplugin.BahnPlugin
version: 1.0
name: BahnPlugin
commands:
  bahn:
    description: Gibt den Bahnhof zu dem angegebenen Spieler zurueck
    usage: "§cUsage: /bahn [set|delete] <spielername> [bahnhof]"
    permission: bahnplugin.use